---
title: "Summer 2025 Report"
---

Riley Wheadon

August 27th, 2025

## Introduction

Between May and August 2025, I translated the flood frequency analysis (FFA) framework described in [Vidrio-Sahagún et al. (2024)](https://doi.org/10.1016/j.envsoft.2024.105940) from MATLAB into R.
This project has two components: An [R package](https://rileywheadon.github.io/ffa-framework/) and a [web application](https://ffaframework.rwheadon.dev/).
The R package is designed to facilitate flexible and reproducible FFA workflows.
It is available on [CRAN](https://cran.r-project.org/web/packages/ffaframework/index.html).
The web application provides a simple GUI for the R package.

### Architecture

The FFA framework is organized into three _modules_:

1. **Data Processing**: Screening and transformation of annual maximum series data.
2. **FFA Approach Selection**: The choice between stationary (S-FFA), nonstationary (NS-FFA), and piecewise nonstationary FFA, guided by exploratory data analysis (EDA).
3. **Flood Frequency Analysis**: Selection of a suitable probability model, estimation of return levels and confidence intervals, and computation of model performance metrics.

The "FFA Approach Selection" module contains three _submodules_:

1. **Change Point Detection**: Identification of trend changes (Mann-Kendall-Sneyers test) and abrupt changes in the mean (Pettitt test).
2. **Trend Detection**: Identification and estimation of monotonic trends in the mean and variability.
3. **Approach Selection**: Using the results of change point detection and trend detection combined with basin-specific knowledge to choose a suitable formalism for FFA.

The "Flood Frequency Analysis" module contains four _submodules_:

1. **Distribution Selection**: Selection of an appropriate probability distribution using the method of L-moments and one of three selection metrics (L-distance, L-kurtosis, Z-statistic).
2. **Parameter Estimation**: Parameter estimation with one of three methods (L-moments, MLE, GMLE).
3. **Uncertainty Quantification**: Estimation of confidence intervals using one of three methods (Parametric bootstrap, RFPL, RFGPL).
4. **Model Assessment**: Regression of the estimates from the parametric model against the data using the method of plotting positions (for S-FFA) or normalized plotting positions (for NS-FFA). Information criterion and uncertainty statistics (using the confidence intervals) are also computed.

Each submodule contains one or more low-level functions implemented in the R package.

### Differences from MATLAB Version

**Bug Fixes** (these bugs have _only_ been fixed in the R version, _not_ in the MATLAB version):

- Only show _significant_ change points in the Pettitt and Mann-Kendall-Sneyers plots.
- Allow the Mann-Kendall-Sneyers test to identify multiple change points.
- Resolve a major issue where the Mann-Kendall-Sneyers test only identified change points based on the progressive series of test statistics instead of the Z-statistics of the crossing points.
- Remove unnecessary rounding in the moving window algorithm for the variability time series.
- Modify the Phillips-Perron and KPSS tests to account for drift and trend.
- Use the log-gamma function to avoid numerical issues during PE3/LP3 parameter estimation.
- Use the `approx()` function to perform log-linear interpolation of the return periods during model assessment. This fixes a numerical issue with the interpolation algorithm in the MATLAB version.

**Changes to the EDA Module**:

- Skip the Phillips-Perron and KPSS tests if serial correlation _is not_ identified. We can do this because serial correlation is a _necessary_ condition for a unit root (stochastic trend).
- Add the Runs test to check if a monotonic trend (estimated using Sen’s trend estimator) is suitable for the data. If the Runs test rejects the null hypothesis, the residuals from Sen's trend estimator are not random, so there is evidence of nonlinear nonstationarity in the data.

**Changes to the FFA Module**:

- Add the 3-parameter Weibull distribution (with location, scale, and shape parameters).
- Switch to a faster, optimization-based approach for L-distance and L-kurtosis model selection.
- Switch to the more precise L-BFGS-B optimization algorithm for MLE/GMLE parameter estimation.

## R Package

Unlike the MATLAB version, the R package is almost entirely _decoupled_, which means that each function, submodule, and module can be run independently.
Only the plotting functions explicitly require the output of another function in the package.

A _lot_ of documentation is available for the R package.

- All R functions are thoroughly documented using `roxygen2` (see [here](https://rileywheadon.github.io/ffa-framework/reference/index.html)).
- Vignettes detailing how to use the R package are available under the "Vignettes" tab.
- Explanations of the statistical concepts behind the FFA Framework are under the "Articles" tab.

The R package is licensed under [AGPL (>=3)](https://www.gnu.org/licenses/agpl-3.0.en.html), which ensures that modified versions of the source code and derivative web applications are distributed under an open source license.
Just to clarify -- _the AGPL license permits all users (including corporations) to modify and redistribute the project, as long as the modified version remains open source_.

The R package is currently available on [CRAN](https://cran.r-project.org/web/packages/ffaframework/index.html).
A few points about this:

1. Hosting the package on CRAN greatly simplifies the installation process. Users of the package only need a single command, `install.packages("ffaframework")`, to get started.
2. CRAN requires maintainers to fix issues within 2 weeks or their package will be removed. I (Riley) will handle this until **September 1st, 2026** (see the "Maintenance Commitments" section below).
3. CRAN permits maintainers to update their packages _at most_ every 1-2 months. However, bleeding edge versions of the R package can always be installed from Github with `devtools`.

## Web App

The web application is built using [Plumber](https://www.rplumber.io/) \(R\), [Flask](https://flask.palletsprojects.com/en/stable/) (Python), as well as various front-end technologies including [AlpineJS](https://alpinejs.dev/), [HTMX](https://htmx.org/), and [TailwindCSS](https://tailwindcss.com/).
No persistent data is stored on the web server, although [Valkey](https://valkey.io/) (an open-source clone of [Redis](https://redis.io/)) is used for storing temporary state.
The entire app is wrapped in a [Docker](https://www.docker.com/) container, which simplifies deployment across different systems.
Any virtual machine that hosts the app should have **at least 4GB of RAM**.
The prototype hosted on [ffaframework.rwheadon.dev](https://ffaframework.rwheadon.dev/) uses a [DigitalOcean](https://www.digitalocean.com/) droplet with 8GB of RAM.

## Next Steps

> ... FFA assumes that the record of observed floods can be treated as independent random variables drawn from a homogeneous and representative population that **remains unchanged over time**.
>
> - [Federal Hydrologic and Hydraulic Procedures for Flood Hazard Delineation, Section 5.4.1](https://natural-resources.canada.ca/science-data/science-research/natural-hazards/flood-mapping/federal-hydrologic-hydraulic-procedures-flood-hazard-delineation)

As shown above, the guidelines for FFA distributed by Environment and Climate Change Canada (ECCC) do not provide instructions on handling nonstationarity.
In my opinion, the long-term goal of our project is to change this.
For our work to become part of the ECCC standard, it must meet existing guidelines for S-FFA while improving on these guidelines by accounting for nonstationarity.
The existing ECCC guidelines can also be improved in other areas, such as data screening and climate-specific concerns.

### Maintenance Commitments

Until **September 1st, 2026** (one year after the _end_ of my work term), I am willing to:

1. Fix any bugs brought to my attention in both the R package and web application.
2. Continue my role as the "Maintainer" of the R package (for CRAN).
3. Handle deployment and maintenance of the web application on DRAC resources.
4. Make any _small_ and _necessary_ changes to ensure the documentation is clear.
5. Deliver presentations about the project in conferences and/or university courses, as long as these presentations can be scheduled without interfering with my other commitments.

If you would like me to continue developing the FFA Framework between September 2025 and April 2026, I would prefer to work as a contractor on a project-by-project basis.
Some project ideas are listed below.
I think I could be able to work ~10 hours a week on these projects after I settle into my new job.

### Project Ideas

**Disclaimer**: The "Estimated Time" and "Significance" columns are _rough estimates_ and could be very wrong.
Please keep in mind that the estimated time _includes_ the following tasks:

1. Conducting preliminary research for the project (reading papers).
2. Writing wiki entries explaining the mathematics/statistics behind the project.
3. Writing _and_ documenting new methods for the R package.
4. Adding the project to the web application.

| Project Title                                         | Estimated Time      | Significance |
| ----------------------------------------------------- | ------------------- | ------------ |
| [Dataset Screening](#dataset-screening)               | 30hrs (2-3 weeks)   | Medium       |
| [Outlier Detection](#outlier-detection)               | 30hrs (2-3 weeks)   | Medium       |
| [Burr Distributions](#burr-distributions)             | 30hrs (2-3 weeks)   | Low          |
| [Distribution Uncertainty](#distribution-uncertainty) | 30hrs (2-3 weeks)   | Medium       |
| [NS Assessment Metrics](#ns-assessment-metrics)       | 60hrs (4-6 weeks)   | Low          |
| [Geophysical Priors](#geophysical-priors)             | 120hrs (9-12 weeks) | High         |
| [Peaks Over Threshold](#peaks-over-threshold)         | 120hrs (9-12 weeks) | High         |
| [Mixed Population Testing](#mixed-population-testing) | 120hrs (9-12 weeks) | High         |
| [Outreach and Education](#outreach-and-education)     | -                   | -            |
| [Additional Projects](#additional-projects)           | -                   | -            |

#### Dataset Screening

Our data processing module currently lacks functionality for detecting data quality issues.
Identifying such issues prior to flood frequency analysis helps prevent users from making potentially serious errors.

This project will involve:

1. Using `tidyhydat` as a data source in both the R package and web application.
2. Adding the raster plot from `CSHS-hydRology` to both the R package and web application.
3. Providing version information with all datasets to aid reproducibility.

#### Outlier Detection

Our data processing module would benefit from additional screening functions to test for high and low outliers.
Low outliers can lead to incorrect results in distribution selection and parameter estimation, while high outliers may indicate that a different physical process generated the annual maxima event.
Informing our users about potential outliers allows them to make important adjustments to the data, improving the quality of the final analysis.

This project will involve:

1. Familiarizing myself with existing literature on outlier detection including [Bulletin 17C (USGS, 2019)](https://pubs.usgs.gov/tm/04/b05/tm4b5.pdf). The multiple Grubbs-Beck test ([Cohn et al., 2013](https://doi.org/10.1002/wrcr.20392)) seems to be a common choice for low outliers.
2. Implementing outlier detection tests in the EDA submodule.
3. Creating a diagnostic plot showing both low and high outliers (or using `CSHS-hydRology`).
4. Updating the web application, documentation, and vignettes as necessary.

#### Burr Distributions

[Zaghloul et al. (2020)](https://www.sciencedirect.com/science/article/pii/S030917082030227X?via%3Dihub) found that the Burr Type III and Burr Type XII distributions fit better to heavy-tailed data across a majority of the climatic regions in Canada.
Adding these distributions to the FFA framework will give modellers more options for annual maxima FFA.

This project will involve:

1. Reading literature, particularly [Zaghloul et al. (2020)](https://doi.org/10.1016/j.advwatres.2020.103720) for a general overview and [Papalexiou & Koutsoyiannis (2016)](https://doi.org/10.1016/j.advwatres.2016.05.005) for information about the L-moments of the Burr distributions.
2. Implementing R functions that compute the L-moments from the Burr distribution parameters (and vice-versa), using approximate methods where necessary.
3. Modifying the L-moment diagram to include the Burr distributions.
4. Updating uncertainty quantification functions to account for the unique parameters of the Burr distributions (scale, shape, shape as opposed to location, scale, shape).
5. Updating the web application, documentation, and vignettes as necessary.

#### Distribution Uncertainty

Current ECCC guidelines recommend the approaches listed below for distribution selection:

1. Using results from a single “best-fit” distribution, where “best fit” is apparent.
2. Using an average or weighted average of all reasonable distributions.
3. Using the most conservative result from a set of “acceptable” distributions.
4. Providing confidence bands for the estimates for the various annual exceedance probabilities.

This project would add approaches 2 and 3 to our framework (approach 1 is already implemented).
We will do this by quantifying uncertainty during distribution selection, using the process described by Martyn Clark during my group meeting presentation.
This will allow us to identify scenarios where multiple distributions are equally good fits for the data.

This project will involve:

1. Designing a bootstrapping procedure (possibly using the 4-parameter Kappa distribution) to generate many simulated samples with similar statistical properties to the observed annual maxima.
2. Constructing confidence intervals for the L-skewness and L-kurtosis of the data.
3. Modifying the L-moment diagram to include the confidence intervals computed in (2).
4. Recommending 0 or more distributions (instead of exactly 1) for parameter estimation.
5. Updating the web application, documentation, and vignettes as necessary.

#### NS Assessment Metrics

The method of plotting positions provides robust model assessment for S-FFA.
However, model assessment becomes more complicated when nonstationarity is present.
Currently, the FFA Framework uses a normalized version of the plotting positions (displayed as a [worm plot](https://doi.org/10.1002/sim.746)) for nonstationary model assessment.
However, users may benefit from having more options.

This project will involve reading the following papers on nonstationary model assessment metrics:

- Expected Waiting Time (EWT): [Olsen et al. 1998](https://doi.org/10.1111/j.1539-6924.1998.tb00364.x); [Wigley, 2009](https://doi.org/10.1007/s10584-009-9654-7)
- Expected Number of Exceedances (ENE): [Parey et al. 2007](https://doi.org/10.1002/env.2252); [Parey et al. 2010](https://doi.org/10.1002/env.1060)
- Effective Return Period (ERP): [Katz et al. 2002](<https://doi.org/10.1016/S0309-1708(02)00056-8>)
- Risk of Failure/Reliability: [Read & Vogel, 2015](https://doi.org/10.1002/2015WR017089); [Salas & Obeysekera, 2014](https://doi.org/10.1080/02626667.2018.1426858); [Serinaldi & Kilsby, 2015](https://doi.org/10.1016/j.advwatres.2014.12.013)
- Design Life Level (DLL): [Rootzen & Katz, 2013](https://doi.org/10.1002/wrcr.20425)
- Average Design Life Level (ADLL): [Yan et al. 2017](https://doi.org/10.1016/j.jhydrol.2017.06.001)

Then, the most promising metrics will be documented and implemented in the R package.
An option will be added to the web application to choose the nonstationary model assessment metric(s) to compute.

#### Geophysical Priors

The Regula-Falsi Profile Likelihood (RFPL) uncertainty quantification method is used to compute confidence intervals for nonstationary models ([Vidrio-Sahagún et al. 2023](https://doi.org/10.1007/s00477-023-02603-0)).
However, RFPL uncertainty quantification is known to be numerically unstable for certain distributions and datasets.
The Regula-Falsi Generalized Profile Likelihood (RFGPL) method, which incorporates a prior distribution on the shape parameter, is known to give more reliable results ([Vidrio-Sahagún & He, 2022](https://doi.org/10.1016/j.advwatres.2022.104151)).

While the RFGPL uncertainty quantification method has already been implemented in the FFA Framework, no recommendations for the prior distribution on the shape parameter are provided.
This project will analyze the shape parameters of fitted flood frequency models at stations across Canada and use the results to recommend suitable prior distributions based on location and climate.

This project will involve:

1. Choosing a representative sample of hydrological monitoring stations throughout Canada.
2. Fitting a variety of flood frequency models to the annual maxima from these stations.
3. Using the distribution of the shape parameters from the fitted models to determine suitable prior distributions for each climatic region in Canada.
4. Surfacing information about the recommended prior distribution for the shape parameter in both the R package and web application.

#### Peaks Over Threshold

Peaks over threshold (POT) is a FFA paradigm that uses all streamflow events above a predetermined threshold.
POT modelling is often performed using the [Generalized Pareto Distribution](https://en.wikipedia.org/wiki/Generalized_Pareto_distribution).
By adding POT modelling to the FFA Framework, we give users an alternative modelling formalism which can then be compared with the existing annual maxima approach.

This project will involve:

1. Reading relevant literature on POT modelling. Determining the minimum time between independent events and choosing an appropriate threshold are areas of particular concern.
2. Implementing functions in the R package to compute the L-moments of the Generalized Pareto Distribution from its parameters (and vice-versa).
3. Implementing new functions for exploratory data analysis, parameter estimation, uncertainty quantification, and model assessment to conform with the POT formalism where necessary.
4. Writing a new vignette for POT modelling and adding a POT mode to the web application.

#### Mixed Population Testing

_This project requires the [Peaks Over Threshold](#peaks-over-threshold) project to be finished first._

In my discussions with Paul Whitfield and Kevin Shook, it has been brought to my attention that floods in Canada can be caused by rainfall (_pluvial_), snow melt (_nival_), or a combination of the two (mixed).
Therefore, a single probability distribution is often not suitable for FFA.

This project will involve:

1. Implementing the algorithm in [Burn & Whitfield (2025)](https://doi.org/10.1080/02626667.2024.2422531) to categorize floods as pluvial, nival, or mixed.
2. Adding a function to the R package that combines fitted POT models across multiple flood categories and estimates general return levels and confidence intervals.
3. Providing the modeller with a recommendation to use mixed population testing in certain scenarios.
4. Writing a new vignette for mixed population testing and updating the web application as necessary.

#### Outreach and Education

I believe that increasing the number of people using our project is the single most important thing we can do in the next 12 months.
Some ideas for facilitating adoption include:

1. **Workshops and Tutorials**: Offer short online workshops or record and share YouTube videos.
2. **Teaching Notebooks**: Provide RMarkdown tutorials or Jupyter notebooks with guided exercises.
3. **Outreach**: Offer the package to other universities/professors as a teaching/research tool.

As mentioned by Paul Whitfield and Kevin Shook, it is important that we provide examples of both good _and_ bad flood frequency analyses to demonstrate the potential pitfalls of our framework.

#### Additional Projects

- Incorporation of ordinary event data as described in [Vidrio-Sahagún & He, 2022](https://doi.org/10.1016/j.advwatres.2022.104244).
- Implementing regional frequency analysis (multiple regression method, index method).

Small Improvements:

- Rework the R package to use tibbles (generated by `tidyhydat`) instead of vectors?
- Redesign the status bar on the web application to work on smaller screen sizes.
- Implement report generation on the web application for PDF, Markdown, and JSON files.
