# Path to folder of data files
data_dir: "~/Code/ffa-framework/data"       

# Name of CSV file in data_path
csv_file: "Application_3.1.csv"                 

# Path for generating reports
report_dir: "~/Code/ffa-framework/reports"  

# Significance level for EDA
alpha_eda: 0.05       

# Number of simulations in BB-MK test
n_sim_eda: 10000      

# Window length in MW-MK test
window_length_eda: 10 

# Window step in MW-MK test
window_step_eda: 5    

