# Path to CSV file 
csv_file: "~/Code/ffa-framework/data/Application_2.csv"                 

# Path for generating reports
report_dir: "~/Code/ffa-framework/reports"  

# Significance level for EDA
alpha: 0.05       

# Number of bootstrap samples in BB-MK test
bb_mk_repetitions: 10000      

# Window length in MW-MK test
window_length_eda: 10 

# Window step in MW-MK test
window_step_eda: 5    

